### PR TITLE
OD-2175: Add Fraud case to Adyen webhook

### PR DESCRIPTION
**Pull request by MPishpecki**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MPishpecki** [comment]
For this to work we need in the transaction creation when importing from Magento to set the **reference** to the Magento SO number, because that is the MerchantReference Adyen will use to communicate the Fraud case
We need tests on this to run :(

**Review by hbrunn — COMMENTED** [review]
code looks good, but is a chargeback always fraud? Can't this also be just silly stuff like insufficient funds? If that's true, I'd suggest to call the function `process_chargeback`

**Review by antonioburic — APPROVED** [review]

**Comment by MPishpecki** [comment]
> code looks good, but is a chargeback always fraud? Can't this also be just silly stuff like insufficient funds? If that's true, I'd suggest to call the function `process_chargeback`

Ah yes -great that you mentioned this. As far as I can read from their documentation here:

https://docs.adyen.com/risk-management/disputes-api/dispute-notifications#notification_of_chargeback

and the reasons that are in the charge-back all point to a fraud
https://docs.adyen.com/risk-management/understanding-disputes/dispute-reason-codes?tab=chargeback_1

**Comment by hbrunn** [comment]
to me a lot of them read like, well, disputes.

D62 The cardholder claims that the goods or services that were purchased at your business have not been received. 

that *could* be fraud, but also an honestly dissatisfied customer

**Comment by MPishpecki** [comment]
@hbrunn I see your point. I focused only on the top part of the document and haven't noticed the code you mention. Since we are creating a new process here I would go in the direction of being more restrictive and only when finance notices that we do over-restriction do we filter only certain codes that are fraud related. 
For now, I see the following logic take precedence: We check for the **eventCode** NOTIFICATION_OF_CHARGEBACK in this case we don't get paid. If we don't get paid we should cancel the order. Any flow where we would involve a CS agent (for example blocks an order and  CS agent figures out what is wrong, sends a payment link and so on) needs to be defined on the business side before we apply it.

Edit: I added a question to the business in this regard https://vmbikes.atlassian.net/browse/OD-2175?focusedCommentId=64865
Edit 2: Panos responded - we should block all charge-backs

**Review by dkubiak789 — APPROVED** [review]

**Pull request merged**
